/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class Diskon extends javax.swing.JPanel {
    
    public void tabel(){
    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nilai Diskon");
        model.addColumn("Nama Diskon");
        model.addColumn("Tanggal Diskon");

        try {
            
            String sql ="SELECT id, nama, tanggal, persen FROM tb_diskon ";
            Connection conn = com.Koneksi.Koneksi.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString(1), rs.getString(4) +"%", rs.getString(2), rs.getString(3)
                });
                
            }
            
            table1.setModel(model);
           
            
        } catch (Exception e) {
            System.out.println(e);
        }
     }

    /**
     * Creates new form Diskon
     */
    public Diskon() {
        initComponents();
        table1.fixTable(jScrollPane1);
        tabel();
//        Connect();
    }
    public void kosong(){
        txt_id12.setText(null);
        txt_namaDiskon.setText(null);
        txt_nilaiDiskon1.setText(null);
        txt_tanggalDiskon.setText(null);
    }
// Connection con;
//    PreparedStatement pst;
//    public void Connect(){
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            try {
//                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_skincare", "root", "");
//            } catch (SQLException ex) {
//                Logger.getLogger(Diskon.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Diskon.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    public void show(String id1,  String nilai_diskon, String nama_diskon, String tanggal_diskon) {
        this.txt_id12.setText(id1);
//        this.txt_nilaiDiskon1.setText(nilai_diskon);
//        this.txt_namaDiskon.setText(nama_diskon);
//        this.txt_tanggalDiskon.setText(tanggal_diskon);
    }
    
    //autoinctrement
   
    public void select1(int konfirm) {
		switch (konfirm) {
			case 0:
				btn_tambah.setVisible(true);
				btn_simpan.setVisible(false);
				btn_hapus.setVisible(false);
				break;
			case 1:
				btn_tambah.setVisible(false);
				btn_simpan.setVisible(true);
				btn_hapus.setVisible(true);
				break;
			default:
				break;
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tanggalDiskon = new javax.swing.JTextField();
        txt_nilaiDiskon1 = new javax.swing.JTextField();
        txt_namaDiskon = new javax.swing.JTextField();
        txt_id12 = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.swing.table.Table();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kalender.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 611, -1, -1));

        txt_tanggalDiskon.setBackground(new java.awt.Color(255, 194, 212));
        txt_tanggalDiskon.setBorder(null);
        txt_tanggalDiskon.setOpaque(false);
        txt_tanggalDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalDiskonActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tanggalDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 614, 130, -1));

        txt_nilaiDiskon1.setBackground(new java.awt.Color(255, 194, 212));
        txt_nilaiDiskon1.setBorder(null);
        txt_nilaiDiskon1.setOpaque(false);
        txt_nilaiDiskon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nilaiDiskon1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nilaiDiskon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 566, 150, -1));

        txt_namaDiskon.setBackground(new java.awt.Color(255, 194, 212));
        txt_namaDiskon.setBorder(null);
        txt_namaDiskon.setOpaque(false);
        txt_namaDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaDiskonActionPerformed(evt);
            }
        });
        jPanel1.add(txt_namaDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 614, 150, -1));

        txt_id12.setBackground(new java.awt.Color(255, 194, 212));
        txt_id12.setBorder(null);
        txt_id12.setOpaque(false);
        txt_id12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id12ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 566, 150, -1));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Button tambah.png"))); // NOI18N
        btn_tambah.setBorder(null);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 557, 125, 30));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Button Simpan.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 604, 125, 30));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Button hapus.png"))); // NOI18N
        btn_hapus.setBorder(null);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 654, 125, 30));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Diskon", "Tanggal", "Persen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 820, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rectangle 53.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 562, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rectangle 53.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 610, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rectangle 53.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rectangle 53.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 562, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tampilan diskon baru2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id12ActionPerformed

    private void txt_namaDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaDiskonActionPerformed

    private void txt_nilaiDiskon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nilaiDiskon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nilaiDiskon1ActionPerformed

    private void txt_tanggalDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalDiskonActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
         try {

            String sql = "INSERT INTO `tb_diskon`(`id`,`nama`,`tanggal`, `persen`) VALUES ('"+txt_id12.getText()+"','"+txt_namaDiskon.getText()+"','"+txt_tanggalDiskon.getText()+"','"+txt_nilaiDiskon1.getText()+"')";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)com.Koneksi.Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         tabel();
         kosong();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
			String sql = "UPDATE `tb_diskon` SET `nama`='"+txt_namaDiskon.getText()+"',persen = '"+txt_nilaiDiskon1.getText()+"',tanggal = '"+txt_tanggalDiskon.getText()+"' where id= '"+txt_id12.getText()+"'";
			System.out.println(sql);
			java.sql.Connection conn = (Connection) com.Koneksi.Koneksi.configDB();
			java.sql.PreparedStatement pst = conn.prepareStatement(sql);
			pst.execute();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
        tabel();
        kosong();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
			String sql = "DELETE FROM tb_diskon WHERE id ='" +txt_id12.getText()+ "'";
                        System.out.println(sql);
			java.sql.Connection conn = (Connection) com.Koneksi.Koneksi.configDB();
			java.sql.PreparedStatement ps = conn.prepareStatement(sql);
			ps.execute();
			JOptionPane.showMessageDialog(null, "Data berhasil di Hapus");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
         tabel();
         kosong();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int baris=table1.getSelectedRow();
        txt_namaDiskon.setText(String.valueOf(table1.getValueAt(baris, 2)));
        txt_id12.setText(String.valueOf(table1.getValueAt(baris, 0)));
        txt_nilaiDiskon1.setText(String.valueOf(table1.getValueAt(baris, 1)));
        txt_tanggalDiskon.setText(String.valueOf(table1.getValueAt(baris, 3)));
    }//GEN-LAST:event_table1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.swing.table.Table table1;
    private javax.swing.JTextField txt_id12;
    private javax.swing.JTextField txt_namaDiskon;
    private javax.swing.JTextField txt_nilaiDiskon1;
    private javax.swing.JTextField txt_tanggalDiskon;
    // End of variables declaration//GEN-END:variables
}
