/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Main;

import com.popup.popup_detail_riwayat;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class Riwayat_Transaksi1 extends javax.swing.JPanel {

	public Riwayat_Transaksi1() {
		initComponents();
		table1.fixTable(jScrollPane1);

		tabelRiwayat("", "");
	}

	private void tabelRiwayat(String date1, String date2) {
		DefaultTableModel model = new DefaultTableModel();
		model.addColumn("ID Barang");
		model.addColumn("Total Harga");
		model.addColumn("Dibayar");
		model.addColumn("Kembalian");
		model.addColumn("Tanggal");
		model.addColumn("ID Pelanggan");
		model.addColumn("ID Akun");
		model.addColumn("ID Diskon");

		try {

			String sql = "select * from tb_transaksi";
			if (date1 != null || date2 != null) {
				sql = sql + " where tanggal between '" + date1 + "' and '" + date2 + "'";
			}
			System.out.println(sql);

			Connection conn = com.Koneksi.Koneksi.configDB();
			PreparedStatement ps = conn.prepareStatement(sql);
			ResultSet rs = ps.executeQuery(sql);
			while (rs.next()) {
				model.addRow(new Object[]{
					rs.getString(1), rs.getString(2), rs.getString(3),
					rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)
				});

			}

			table1.setModel(model);

		} catch (SQLException e) {
			System.out.println(e);
		}
	}

	private boolean compareDate() {
		boolean isAfter = false;

		try {
			SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
			Date date1 = format.parse(this.date1.getText());
			Date date2 = format.parse(this.date2.getText());

			// ngereturn boolean kalo date1 itu sama apa ngga sama date2 atau lebih dari
			isAfter = date1.equals(date2) || date1.after(date2);

		} catch (ParseException ex) {

		}
		return isAfter;
	}

	private void verifyFields() {
		if (date1.getText().length() == 0 || date2.getText().length() == 0) {
			System.out.println("Mohon isi rentang jadwal terlebih dahulu");
		} else if (compareDate()) {
			System.out.println("Tanggal lebih atau sama");
		} else {
			tabelRiwayat(date1.getText(), date2.getText());
		}

	}

	private void getPDF() {
		String filename = null;
		String sql = "select * from tb_transaksi";

		filename = "C:\\Users\\" + System.getProperty("user.name") + "\\Documents\\Data-Skincare.csv";

		try {
			try (FileWriter fw = new FileWriter(filename)) {
				fw.append("ID Transaksi");
				fw.append(',');
				fw.append("Total Harga");
				fw.append(',');
				fw.append("Dibayar");
				fw.append(',');
				fw.append("Kembalian");
				fw.append(',');
				fw.append("Tanggal");
				fw.append(',');
				fw.append("ID Pelanggan");
				fw.append(',');
				fw.append("ID Akun");
				fw.append(',');
				fw.append("ID Diskon");
				fw.append(',');
				fw.append('\n');

				java.sql.Connection conn = (Connection) com.Koneksi.Koneksi.configDB();
				java.sql.PreparedStatement ps = conn.prepareStatement(sql);
				java.sql.ResultSet rs = ps.executeQuery(sql);

				while (rs.next()) {
					fw.append(rs.getString(1));
					fw.append(',');
					fw.append(rs.getString(2));
					fw.append(',');
					fw.append(rs.getString(3));
					fw.append(',');
					fw.append(rs.getString(4));
					fw.append(',');
					fw.append(rs.getString(5));
					fw.append(',');
					fw.append(rs.getString(6));
					fw.append(',');
					fw.append(rs.getString(7));
					fw.append(',');
					fw.append(rs.getString(8));
					fw.append('\n');
				}
				fw.flush();
			}
		} catch (SQLException | IOException e) {
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                dateChooser1 = new com.swing.datechooser.DateChooser();
                dateChooser2 = new com.swing.datechooser.DateChooser();
                jPanel1 = new javax.swing.JPanel();
                date1 = new javax.swing.JTextField();
                date2 = new javax.swing.JTextField();
                search = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                table1 = new com.swing.table.Table();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                dateChooser1.setDateFormat("yyyy-MM-dd");
                dateChooser1.setTextRefernce(date1);

                dateChooser2.setDateFormat("yyyy-MM-dd");
                dateChooser2.setTextRefernce(date2);

                jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                date1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                date1ActionPerformed(evt);
                        }
                });
                jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 120, 20));
                jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 130, 20));

                search.setBackground(new java.awt.Color(255, 224, 233));
                search.setBorder(null);
                search.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchActionPerformed(evt);
                        }
                });
                search.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                searchKeyReleased(evt);
                        }
                });
                jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 54, 150, -1));

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Button Export.png"))); // NOI18N
                jButton1.setBorder(null);
                jButton1.setContentAreaFilled(false);
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 660, 125, -1));

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tanggal.png"))); // NOI18N
                jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 50, -1, -1));

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tanggal.png"))); // NOI18N
                jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel6MouseClicked(evt);
                        }
                });
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 50, -1, -1));

                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/-.png"))); // NOI18N
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1121, 60, -1, -1));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sort By Date.png"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 53, -1, -1));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Search (2).png"))); // NOI18N
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 50, -1, -1));

                table1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Id Transaksi", "Total Harga", "Dibayar ", "Kembalian", "Tanggal Transaksi"
                        }
                ));
                table1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                table1MouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table1);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 1020, 495));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Background Table.png"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 83, -1, -1));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desktop - 8.png"))); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
	    // TODO add your handling code here:
	    tabelRiwayat(null, null);
    }//GEN-LAST:event_searchKeyReleased

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
	    int row = table1.rowAtPoint(evt.getPoint());
	    String one = table1.getValueAt(row, 0).toString();
	    // TODO add your handling code here:
	    popup_detail_riwayat riwayat = new popup_detail_riwayat(null, true, one);
	    riwayat.setVisible(true);
    }//GEN-LAST:event_table1MouseClicked

        private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_jLabel6MouseClicked

        private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
		// TODO add your handling code here:
		dateChooser1.showPopup();
        }//GEN-LAST:event_date1ActionPerformed

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
		// TODO add your handling code here:
		verifyFields();
        }//GEN-LAST:event_jLabel3MouseClicked

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		getPDF();
        }//GEN-LAST:event_jButton1ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField date1;
        private javax.swing.JTextField date2;
        private com.swing.datechooser.DateChooser dateChooser1;
        private com.swing.datechooser.DateChooser dateChooser2;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField search;
        private com.swing.table.Table table1;
        // End of variables declaration//GEN-END:variables
}
